# STARSHIP PROMPT -- https://starship.rs/

command_timeout = 1500

[aws]
symbol = "  "
format = '[$symbol($profile)(\($region\))($duration)]($style) '

[[battery.display]]
threshold = 15

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[cmake]
format = '[$symbol]($style) '

[cmd_duration]
disabled = true

[conda]
symbol = " "
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol]($style) '

[dart]
symbol = " "
format = '[$symbol]($style) '

[deno]
format = '[$symbol]($style) '

[directory]
read_only = " "

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol(🎯 $tfm)]($style) '

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\))]($style) '

[elm]
symbol = " "
format = '[$symbol]($style) '

[erlang]
format = '[$symbol]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = " "
format = '[$symbol$branch]($style)'

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "yellow"
format = '([$all_status$ahead_behind]($style)) '

[golang]
symbol = " "
style = "bold blue"
format = '[$symbol]($style) '

[helm]
format = '[$symbol]($style) '

[hg_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[java]
symbol = " "
format = '[$symbol]($style) '

[julia]
symbol = " "
format = '[$symbol]($style) '

[kotlin]
format = '[$symbol]($style) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
format = '[$symbol]($style) '

[memory_usage]
symbol = " "
format = '$symbol[$ram( | $swap)]($style) '

[nim]
symbol = " "
format = '[$symbol]($style) '

[nix_shell]
symbol = " "
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
format = '[$symbol]($style) '

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\))]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[package]
symbol = " "
format = '[$symbol$version]($style) '

[perl]
symbol = " "
format = '[$symbol]($style) '

[php]
symbol = " "
format = '[$symbol]($style) '

[purescript]
format = '[$symbol]($style) '

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[red]
format = '[$symbol]($style) '

[ruby]
symbol = " "
format = '[$symbol]($style) '

[rust]
symbol = " "
format = '[$symbol]($style) '

[scala]
symbol = " "
format = '[$symbol]($style) '

[shell]
fish_indicator = ""
powershell_indicator = "_"
bash_indicator = "⌯"
zsh_indicator = "❃"
unknown_indicator = "?"
disabled = false

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
format = '[$symbol]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '

[username]
format = '[$user]($style) '

[vagrant]
format = '[$symbol]($style) '

[vlang]
format = '[$symbol]($style) '

[zig]
format = '[$symbol]($style) '
